In [1]:
#import necessary libraries
import pandas as pd
from pandas import DataFrame
import numpy
import matplotlib.pyplot as plt
import glob
import os

In [2]:
#open files and check dataframes
df1= pd.read_csv('dstrCAW_1.csv')
df2= pd.read_csv('dstrCAW_2013.csv')
df3= pd.read_csv('dstrCAW_1_2014.csv')
df1

,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
0,ANDHRA PRADESH,ADILABAD,2001,50,30,16,149,34,175,0
1,ANDHRA PRADESH,ANANTAPUR,2001,23,30,7,118,24,154,0
2,ANDHRA PRADESH,CHITTOOR,2001,27,34,14,112,83,186,0
3,ANDHRA PRADESH,CUDDAPAH,2001,20,20,17,126,38,57,0
4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26,12,109,58,247,0
5,ANDHRA PRADESH,GUNTAKAL RLY.,2001,0,0,0,1,0,0,0
6,ANDHRA PRADESH,GUNTUR,2001,54,51,7,139,129,378,0
7,ANDHRA PRADESH,HYDERABAD CITY,2001,37,39,24,118,27,746,0
8,ANDHRA PRADESH,KARIMNAGAR,2001,56,49,62,414,81,224,0
9,ANDHRA PRADESH,KHAMMAM,2001,47,30,17,180,336,172,0
10,ANDHRA PRADESH,KRISHNA,2001,37,21,10,208,72,265,0
11,ANDHRA PRADESH,KURNOOL,2001,29,47,13,141,107,92,0
12,ANDHRA PRADESH,MAHABOOBNAGAR,2001,59,27,14,176,41,69,0
13,ANDHRA PRADESH,MEDAK,2001,35,20,26,100,25,192,0
14,ANDHRA PRADESH,NALGONDA,2001,35,19,31,188,59,214,0
15,ANDHRA PRADESH,NELLORE,2001,46,80,10,207,228,287,0
16,ANDHRA PRADESH,NIZAMABAD,2001,21,21,19,55,15,228,0
17,ANDHRA PRADESH,PRAKASHAM,2001,19,12,5,140,100,119,0
18,ANDHRA PRADESH,RANGA REDDY,2001,72,83,37,113,55,421,7
19,ANDHRA PRADESH,SECUNDERABAD RLY.,2001,0,0,1,0,1,0,0
20,ANDHRA PRADESH,SRIKAKULAM,2001,8,12,6,38,47,108,0
21,ANDHRA PRADESH,VIJAYAWADA,2001,25,48,2,84,122,520,0
22,ANDHRA PRADESH,VIJAYAWADA RLY.,2001,1,0,0,1,1,0,0
23,ANDHRA PRADESH,VISAKHA RURAL,2001,12,12,3,67,48,99,0
24,ANDHRA PRADESH,VISAKHAPATNAM,2001,13,6,0,33,462,204,0
25,ANDHRA PRADESH,VIZIANAGARAM,2001,8,2,0,40,22,121,0
26,ANDHRA PRADESH,WARANGAL,2001,53,25,52,241,0,165,0
27,ANDHRA PRADESH,WEST GODAVARI,2001,61,21,15,246,56,348,0
28,ANDHRA PRADESH,TOTAL,2001,871,765,420,3544,2271,5791,7
29,ARUNACHAL PRADESH,CHANGLANG,2001,1,2,0,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8987,CHANDIGARH,CHANDIGARH,2012,27,66,5,45,25,73,0
8988,CHANDIGARH,TOTAL,2012,27,66,5,45,25,73,0
8989,D & N HAVELI,D and N HAVELI,2012,3,9,0,2,0,0,0
8990,D & N HAVELI,TOTAL,2012,3,9,0,2,0,0,0
8991,DAMAN & DIU,DAMAN,2012,5,0,0,0,0,1,0
8992,DAMAN & DIU,DIU,2012,0,0,0,0,0,2,0
8993,DAMAN & DIU,TOTAL,2012,5,0,0,0,0,3,0
8994,DELHI,CAW,2012,0,0,0,0,0,178,0
8995,DELHI,CENTRAL,2012,31,95,4,47,12,57,0
8996,DELHI,CRIME BRANCH,2012,1,1,0,0,0,0,0
8997,DELHI,DELHI UT TOTAL,2012,706,2160,134,727,208,1985,0
8998,DELHI,EAST,2012,90,251,7,96,26,202,0
8999,DELHI,EOW,2012,0,0,0,0,0,0,0
9000,DELHI,GRP(RLY),2012,4,12,1,12,6,0,0
9001,DELHI,IGI AIRPORT,2012,0,0,0,6,0,0,0
9002,DELHI,NEW DELHI,2012,5,13,0,29,7,4,0
9003,DELHI,NORTH,2012,14,84,6,29,10,70,0
9004,DELHI,NORTH-EAST,2012,78,263,25,69,9,293,0
9005,DELHI,NORTH-WEST,2012,64,184,12,19,14,212,0
9006,DELHI,OUTER,2012,67,317,15,79,18,244,0
9007,DELHI,SOUTH,2012,70,134,17,59,36,68,0
9008,DELHI,SOUTH-EAST,2012,116,306,11,160,43,123,0
9009,DELHI,SOUTH-WEST,2012,87,244,18,69,21,207,0
9010,DELHI,STF,2012,0,0,0,0,0,0,0
9011,DELHI,WEST,2012,79,256,18,53,6,327,0
9012,LAKSHADWEEP,LAKSHADWEEP,2012,0,0,0,1,0,1,0
9013,LAKSHADWEEP,TOTAL,2012,0,0,0,1,0,1,0
9014,PUDUCHERRY,KARAIKAL,2012,6,2,0,2,0,1,0
9015,PUDUCHERRY,PUDUCHERRY,2012,7,14,0,7,2,5,0
9016,PUDUCHERRY,TOTAL,2012,13,16,0,9,2,6,0

In [3]:
pd.set_option('display.max_columns', None)
df2

,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
0,Andhra Pradesh,ADILABAD,2013,61,47,12,197,138,464,0
1,Andhra Pradesh,ANANTAPUR,2013,28,84,23,337,43,161,0
2,Andhra Pradesh,CHITTOOR,2013,31,27,13,119,84,435,0
3,Andhra Pradesh,CUDDAPAH,2013,19,50,9,318,163,207,0
4,Andhra Pradesh,CYBERABAD,2013,138,129,43,350,338,1526,0
5,Andhra Pradesh,EAST GODAVARI,2013,74,33,15,352,222,483,0
6,Andhra Pradesh,GUNTAKAL RLY.,2013,0,0,0,3,2,0,0
7,Andhra Pradesh,GUNTUR,2013,38,54,16,296,135,608,0
8,Andhra Pradesh,GUNTUR URBAN,2013,28,34,7,124,93,326,0
9,Andhra Pradesh,HYDERABAD CITY,2013,101,52,39,225,90,1480,0
10,Andhra Pradesh,KARIMNAGAR,2013,57,103,39,354,276,670,0
11,Andhra Pradesh,KHAMMAM,2013,100,104,15,254,297,768,0
12,Andhra Pradesh,KRISHNA,2013,58,37,14,387,274,708,0
13,Andhra Pradesh,KURNOOL,2013,26,50,11,374,199,203,0
14,Andhra Pradesh,MAHABOOBNAGAR,2013,117,63,33,219,98,234,0
15,Andhra Pradesh,MEDAK,2013,64,38,25,169,73,476,0
16,Andhra Pradesh,NALGONDA,2013,77,110,27,367,313,327,0
17,Andhra Pradesh,NELLORE,2013,26,81,8,263,221,374,0
18,Andhra Pradesh,NIZAMABAD,2013,49,33,17,142,295,732,0
19,Andhra Pradesh,PRAKASHAM,2013,39,57,8,298,26,484,0
20,Andhra Pradesh,RAJAHMUNDRY,2013,14,4,2,67,68,209,0
21,Andhra Pradesh,RANGA REDDY,2013,37,25,14,69,23,168,0
22,Andhra Pradesh,SECUNDERABAD RLY.,2013,0,2,0,11,0,0,0
23,Andhra Pradesh,SRIKAKULAM,2013,42,23,3,207,129,361,0
24,Andhra Pradesh,TIRUPATHI URBAN,2013,10,15,7,45,31,133,0
25,Andhra Pradesh,VIJAYAWADA CITY,2013,48,45,12,249,456,1227,0
26,Andhra Pradesh,VIJAYAWADA RLY.,2013,1,1,2,6,5,0,0
27,Andhra Pradesh,VISAKHA RURAL,2013,32,23,8,139,79,210,0
28,Andhra Pradesh,VISAKHAPATNAM,2013,67,50,8,149,100,548,0
29,Andhra Pradesh,VIZIANAGARAM,2013,42,25,10,165,95,383,0
...,...,...,...,...,...,...,...,...,...,...
793,Chandigarh,ZZ TOTAL,2013,45,174,1,143,26,92,0
794,D&N Haveli,D&N HAVELI,2013,5,11,0,1,1,1,0
795,D&N Haveli,ZZ TOTAL,2013,5,11,0,1,1,1,0
796,Daman & Diu,DAMAN,2013,7,4,0,2,0,2,0
797,Daman & Diu,DIU,2013,1,2,0,0,0,0,0
798,Daman & Diu,ZZ TOTAL,2013,8,6,0,2,0,2,0
799,Delhi UT,CAW,2013,0,0,0,1,0,202,0
800,Delhi UT,CENTRAL,2013,71,113,2,174,28,50,0
801,Delhi UT,CRIME BRANCH,2013,4,0,0,0,0,0,0
802,Delhi UT,EAST,2013,210,428,11,364,133,246,0
803,Delhi UT,EOW,2013,0,0,0,0,0,0,0
804,Delhi UT,GRP(RLY),2013,4,5,0,11,1,0,0
805,Delhi UT,IGI AIRPORT,2013,0,1,0,9,5,0,0
806,Delhi UT,METRO RAIL,2013,0,4,1,16,12,2,0
807,Delhi UT,NEW DELHI,2013,19,35,1,66,25,17,0
808,Delhi UT,NORTH,2013,53,151,9,164,25,107,0
809,Delhi UT,NORTH-EAST,2013,183,513,27,333,30,438,0
810,Delhi UT,NORTH-WEST,2013,143,343,17,301,45,236,0
811,Delhi UT,OUTER,2013,178,530,14,332,155,466,0
812,Delhi UT,SOUTH,2013,163,328,10,539,140,117,0
813,Delhi UT,SOUTH-EAST,2013,230,404,16,386,95,220,0
814,Delhi UT,SOUTH-WEST,2013,194,330,14,419,128,403,0
815,Delhi UT,STF,2013,0,0,0,0,0,0,0
816,Delhi UT,WEST,2013,184,424,22,400,94,529,0
817,Delhi UT,ZZ TOTAL,2013,1636,3609,144,3515,916,3033,0
818,Lakshadweep,LAKSHADWEEP,2013,2,0,0,1,0,0,0
819,Lakshadweep,ZZ TOTAL,2013,2,0,0,1,0,0,0
820,Puducherry,KARAIKAL,2013,6,2,1,1,1,1,0
821,Puducherry,PUDUCHERRY,2013,11,23,0,11,7,7,0
822,Puducherry,ZZ TOTAL,2013,17,25,1,12,8,8,0

In [4]:
#taking out fields that cannot be joined with data from previous years
df4= df3[['States/UTs','District', 'Year','Rape','Kidnapping & Abduction_Total','Dowry Deaths','Assault on Women with intent to outrage her Modesty_Total','Insult to the Modesty of Women_Total','Cruelty by Husband or his Relatives','Importation of Girls from Foreign Country']]
df4

,States/UTs,District,Year,Rape,Kidnapping & Abduction_Total,Dowry Deaths,Assault on Women with intent to outrage her Modesty_Total,Insult to the Modesty of Women_Total,Cruelty by Husband or his Relatives,Importation of Girls from Foreign Country
0,Andhra Pradesh,Anantapur,2014,35,106,25,436,26,165,0
1,Andhra Pradesh,Chittoor,2014,32,34,17,135,94,278,0
2,Andhra Pradesh,Cuddapah,2014,28,16,16,215,12,91,0
3,Andhra Pradesh,East Godavari,2014,85,25,7,519,62,464,0
4,Andhra Pradesh,Guntakal Railway,2014,0,0,0,0,0,0,0
5,Andhra Pradesh,Guntur,2014,49,46,16,245,347,454,0
6,Andhra Pradesh,Guntur Urban,2014,40,56,12,160,452,345,0
7,Andhra Pradesh,Krishna,2014,80,34,8,354,232,613,0
8,Andhra Pradesh,Kurnool,2014,32,37,12,403,251,362,0
9,Andhra Pradesh,Nellore,2014,58,124,14,295,205,362,0
10,Andhra Pradesh,Prakasham,2014,50,50,8,197,16,402,0
11,Andhra Pradesh,Rajahmundry,2014,35,8,3,121,27,190,0
12,Andhra Pradesh,Srikakulam,2014,40,10,3,214,91,298,0
13,Andhra Pradesh,Tirupathi Urban,2014,18,17,13,60,21,167,0
14,Andhra Pradesh,Vijayawada City,2014,64,27,10,279,212,642,0
15,Andhra Pradesh,Vijayawada Railway,2014,0,2,2,8,6,1,0
16,Andhra Pradesh,Visakha Rural,2014,38,15,4,129,57,166,0
17,Andhra Pradesh,Visakhapatnam,2014,84,50,13,147,112,371,0
18,Andhra Pradesh,Vizianagaram,2014,47,19,8,225,327,330,0
19,Andhra Pradesh,West Godavari,2014,146,45,24,405,99,661,0
20,Andhra Pradesh,Total,2014,961,721,215,4547,2649,6362,0
21,Arunachal Pradesh,Anjaw,2014,0,1,0,1,0,0,0
22,Arunachal Pradesh,Changlang,2014,6,6,0,0,0,0,0
23,Arunachal Pradesh,Crime Branch,2014,0,0,0,0,0,0,0
24,Arunachal Pradesh,Dibang Valley,2014,1,0,0,0,0,0,0
25,Arunachal Pradesh,Kameng East,2014,1,1,0,6,0,0,0
26,Arunachal Pradesh,Kameng West,2014,0,2,0,9,0,2,0
27,Arunachal Pradesh,Kukung Kumey,2014,3,0,0,1,0,0,0
28,Arunachal Pradesh,Lohit,2014,7,25,0,13,0,1,0
29,Arunachal Pradesh,Longding,2014,3,4,0,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...
807,D&N Haveli,D&N Haveli,2014,5,7,0,2,1,6,0
808,D&N Haveli,Total,2014,5,7,0,2,1,6,0
809,Daman & Diu,Daman,2014,2,1,0,2,0,1,0
810,Daman & Diu,Diu,2014,0,0,0,1,0,0,0
811,Daman & Diu,Total,2014,2,1,0,3,0,1,0
812,Delhi UT,Central,2014,91,169,7,212,37,99,0
813,Delhi UT,Crime Branch,2014,1,1,0,1,0,0,0
814,Delhi UT,East,2014,230,346,15,446,114,477,0
815,Delhi UT,EOW,2014,0,0,0,2,0,0,0
816,Delhi UT,IGI Airport,2014,0,0,0,12,4,0,0
817,Delhi UT,Metro,2014,1,2,0,28,3,0,0
818,Delhi UT,New Delhi,2014,20,25,2,56,18,15,0
819,Delhi UT,North,2014,60,149,6,180,18,117,0
820,Delhi UT,North-East,2014,237,578,27,492,50,349,0
821,Delhi UT,North-West,2014,165,354,14,404,51,246,0
822,Delhi UT,Outer,2014,259,688,22,428,146,521,0
823,Delhi UT,RAILWAY,2014,1,8,0,19,1,0,0
824,Delhi UT,South,2014,280,369,6,595,665,143,0
825,Delhi UT,South-East,2014,266,402,24,469,123,312,0
826,Delhi UT,South-West,2014,234,397,17,494,68,318,0
827,Delhi UT,Spl Cell,2014,0,0,0,0,0,0,0
828,Delhi UT,SPUWAC,2014,0,0,0,0,0,160,0
829,Delhi UT,Vigilance,2014,0,0,0,0,0,0,0
830,Delhi UT,West,2014,251,546,13,484,63,416,0
831,Delhi UT,Total,2014,2096,4034,153,4322,1361,3173,0
832,Lakshadweep,Lakshadweep,2014,1,0,0,1,2,0,0
833,Lakshadweep,Total,2014,1,0,0,1,2,0,0
834,Puducherry,Karaikal,2014,3,1,0,12,1,1,0
835,Puducherry,Puducherry,2014,7,6,1,20,7,3,0
836,Puducherry,Total,2014,10,7,1,32,8,4,0

In [7]:
#renaming columns to concatonate data frames
df4 = df4.rename(columns = {
    'States/UTs':'STATE/UT',
    'District':'DISTRICT',
    'Year':'Year',
    'Rape':'Rape',
    'Kidnapping & Abduction_Total':'Kidnapping and Abduction',
    'Dowry Deaths':'Dowry Deaths',
    'Assault on Women with intent to outrage her Modesty_Total':'Assault on women with intent to outrage her modesty',
    'Insult to the Modesty of Women_Total':'Insult to modesty of Women',
    'Cruelty by Husband or his Relatives':'Cruelty by Husband or his Relatives',
    'Importation of Girls from Foreign Country':'Importation of Girls',
})
#concatonating data from previous years
frames = [df1, df2, df4]
df = pd.concat(frames)
df.columns = map(str.lower, df.columns) # lowercase headers
df= df.rename(columns = { #remove slash from variable name, and rename to more suitable and shorter names
    'state/ut': 'state_ut',
    'kidnapping and abduction':'kidnapping_abduction',
    'dowry deaths':'dowry_deaths',
    'assault on women with intent to outrage her modesty' : 'assault_intnt_outrage_modesty',
    'insult to modesty of women': 'inslt_modesty_women',
    'cruelty by husband or his relatives': 'cruelty_husban_reltvs',
    'importation of girls':'in_trafficking'})
df.state_ut = df.state_ut.str.lower()
df.district = df.district.str.lower()
df

,state_ut,district,year,rape,kidnapping_abduction,dowry_deaths,assault_intnt_outrage_modesty,inslt_modesty_women,cruelty_husban_reltvs,in_trafficking
0,andhra pradesh,adilabad,2001,50,30,16,149,34,175,0
1,andhra pradesh,anantapur,2001,23,30,7,118,24,154,0
2,andhra pradesh,chittoor,2001,27,34,14,112,83,186,0
3,andhra pradesh,cuddapah,2001,20,20,17,126,38,57,0
4,andhra pradesh,east godavari,2001,23,26,12,109,58,247,0
5,andhra pradesh,guntakal rly.,2001,0,0,0,1,0,0,0
6,andhra pradesh,guntur,2001,54,51,7,139,129,378,0
7,andhra pradesh,hyderabad city,2001,37,39,24,118,27,746,0
8,andhra pradesh,karimnagar,2001,56,49,62,414,81,224,0
9,andhra pradesh,khammam,2001,47,30,17,180,336,172,0
10,andhra pradesh,krishna,2001,37,21,10,208,72,265,0
11,andhra pradesh,kurnool,2001,29,47,13,141,107,92,0
12,andhra pradesh,mahaboobnagar,2001,59,27,14,176,41,69,0
13,andhra pradesh,medak,2001,35,20,26,100,25,192,0
14,andhra pradesh,nalgonda,2001,35,19,31,188,59,214,0
15,andhra pradesh,nellore,2001,46,80,10,207,228,287,0
16,andhra pradesh,nizamabad,2001,21,21,19,55,15,228,0
17,andhra pradesh,prakasham,2001,19,12,5,140,100,119,0
18,andhra pradesh,ranga reddy,2001,72,83,37,113,55,421,7
19,andhra pradesh,secunderabad rly.,2001,0,0,1,0,1,0,0
20,andhra pradesh,srikakulam,2001,8,12,6,38,47,108,0
21,andhra pradesh,vijayawada,2001,25,48,2,84,122,520,0
22,andhra pradesh,vijayawada rly.,2001,1,0,0,1,1,0,0
23,andhra pradesh,visakha rural,2001,12,12,3,67,48,99,0
24,andhra pradesh,visakhapatnam,2001,13,6,0,33,462,204,0
25,andhra pradesh,vizianagaram,2001,8,2,0,40,22,121,0
26,andhra pradesh,warangal,2001,53,25,52,241,0,165,0
27,andhra pradesh,west godavari,2001,61,21,15,246,56,348,0
28,andhra pradesh,total,2001,871,765,420,3544,2271,5791,7
29,arunachal pradesh,changlang,2001,1,2,0,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...
807,d&n haveli,d&n haveli,2014,5,7,0,2,1,6,0
808,d&n haveli,total,2014,5,7,0,2,1,6,0
809,daman & diu,daman,2014,2,1,0,2,0,1,0
810,daman & diu,diu,2014,0,0,0,1,0,0,0
811,daman & diu,total,2014,2,1,0,3,0,1,0
812,delhi ut,central,2014,91,169,7,212,37,99,0
813,delhi ut,crime branch,2014,1,1,0,1,0,0,0
814,delhi ut,east,2014,230,346,15,446,114,477,0
815,delhi ut,eow,2014,0,0,0,2,0,0,0
816,delhi ut,igi airport,2014,0,0,0,12,4,0,0
817,delhi ut,metro,2014,1,2,0,28,3,0,0
818,delhi ut,new delhi,2014,20,25,2,56,18,15,0
819,delhi ut,north,2014,60,149,6,180,18,117,0
820,delhi ut,north-east,2014,237,578,27,492,50,349,0
821,delhi ut,north-west,2014,165,354,14,404,51,246,0
822,delhi ut,outer,2014,259,688,22,428,146,521,0
823,delhi ut,railway,2014,1,8,0,19,1,0,0
824,delhi ut,south,2014,280,369,6,595,665,143,0
825,delhi ut,south-east,2014,266,402,24,469,123,312,0
826,delhi ut,south-west,2014,234,397,17,494,68,318,0
827,delhi ut,spl cell,2014,0,0,0,0,0,0,0
828,delhi ut,spuwac,2014,0,0,0,0,0,160,0
829,delhi ut,vigilance,2014,0,0,0,0,0,0,0
830,delhi ut,west,2014,251,546,13,484,63,416,0
831,delhi ut,total,2014,2096,4034,153,4322,1361,3173,0
832,lakshadweep,lakshadweep,2014,1,0,0,1,2,0,0
833,lakshadweep,total,2014,1,0,0,1,2,0,0
834,puducherry,karaikal,2014,3,1,0,12,1,1,0
835,puducherry,puducherry,2014,7,6,1,20,7,3,0
836,puducherry,total,2014,10,7,1,32,8,4,0

In [10]:
# dropping records with totals
df = df[(df.district != 'total')]
df = df[(df.district != 'delhi ut total')]
df = df[(df.district != 'zz total')]
df

,state_ut,district,year,rape,kidnapping_abduction,dowry_deaths,assault_intnt_outrage_modesty,inslt_modesty_women,cruelty_husban_reltvs,in_trafficking
0,andhra pradesh,adilabad,2001,50,30,16,149,34,175,0
1,andhra pradesh,anantapur,2001,23,30,7,118,24,154,0
2,andhra pradesh,chittoor,2001,27,34,14,112,83,186,0
3,andhra pradesh,cuddapah,2001,20,20,17,126,38,57,0
4,andhra pradesh,east godavari,2001,23,26,12,109,58,247,0
5,andhra pradesh,guntakal rly.,2001,0,0,0,1,0,0,0
6,andhra pradesh,guntur,2001,54,51,7,139,129,378,0
7,andhra pradesh,hyderabad city,2001,37,39,24,118,27,746,0
8,andhra pradesh,karimnagar,2001,56,49,62,414,81,224,0
9,andhra pradesh,khammam,2001,47,30,17,180,336,172,0
10,andhra pradesh,krishna,2001,37,21,10,208,72,265,0
11,andhra pradesh,kurnool,2001,29,47,13,141,107,92,0
12,andhra pradesh,mahaboobnagar,2001,59,27,14,176,41,69,0
13,andhra pradesh,medak,2001,35,20,26,100,25,192,0
14,andhra pradesh,nalgonda,2001,35,19,31,188,59,214,0
15,andhra pradesh,nellore,2001,46,80,10,207,228,287,0
16,andhra pradesh,nizamabad,2001,21,21,19,55,15,228,0
17,andhra pradesh,prakasham,2001,19,12,5,140,100,119,0
18,andhra pradesh,ranga reddy,2001,72,83,37,113,55,421,7
19,andhra pradesh,secunderabad rly.,2001,0,0,1,0,1,0,0
20,andhra pradesh,srikakulam,2001,8,12,6,38,47,108,0
21,andhra pradesh,vijayawada,2001,25,48,2,84,122,520,0
22,andhra pradesh,vijayawada rly.,2001,1,0,0,1,1,0,0
23,andhra pradesh,visakha rural,2001,12,12,3,67,48,99,0
24,andhra pradesh,visakhapatnam,2001,13,6,0,33,462,204,0
25,andhra pradesh,vizianagaram,2001,8,2,0,40,22,121,0
26,andhra pradesh,warangal,2001,53,25,52,241,0,165,0
27,andhra pradesh,west godavari,2001,61,21,15,246,56,348,0
29,arunachal pradesh,changlang,2001,1,2,0,3,0,0,0
30,arunachal pradesh,dibang valley,2001,2,4,0,4,0,2,0
...,...,...,...,...,...,...,...,...,...,...
799,west bengal,uttar dinajpur,2014,187,309,9,157,13,779,0
801,a&n islands,south andaman,2014,19,9,3,27,4,10,0
802,a&n islands,north & middle andaman,2014,11,8,0,14,1,4,0
803,a&n islands,nicobar,2014,2,0,0,0,0,0,0
805,chandigarh,chandigarh,2014,59,133,2,87,2,141,0
807,d&n haveli,d&n haveli,2014,5,7,0,2,1,6,0
809,daman & diu,daman,2014,2,1,0,2,0,1,0
810,daman & diu,diu,2014,0,0,0,1,0,0,0
812,delhi ut,central,2014,91,169,7,212,37,99,0
813,delhi ut,crime branch,2014,1,1,0,1,0,0,0
814,delhi ut,east,2014,230,346,15,446,114,477,0
815,delhi ut,eow,2014,0,0,0,2,0,0,0
816,delhi ut,igi airport,2014,0,0,0,12,4,0,0
817,delhi ut,metro,2014,1,2,0,28,3,0,0
818,delhi ut,new delhi,2014,20,25,2,56,18,15,0
819,delhi ut,north,2014,60,149,6,180,18,117,0
820,delhi ut,north-east,2014,237,578,27,492,50,349,0
821,delhi ut,north-west,2014,165,354,14,404,51,246,0
822,delhi ut,outer,2014,259,688,22,428,146,521,0
823,delhi ut,railway,2014,1,8,0,19,1,0,0
824,delhi ut,south,2014,280,369,6,595,665,143,0
825,delhi ut,south-east,2014,266,402,24,469,123,312,0
826,delhi ut,south-west,2014,234,397,17,494,68,318,0
827,delhi ut,spl cell,2014,0,0,0,0,0,0,0
828,delhi ut,spuwac,2014,0,0,0,0,0,160,0
829,delhi ut,vigilance,2014,0,0,0,0,0,0,0
830,delhi ut,west,2014,251,546,13,484,63,416,0
832,lakshadweep,lakshadweep,2014,1,0,0,1,2,0,0
834,puducherry,karaikal,2014,3,1,0,12,1,1,0
835,puducherry,puducherry,2014,7,6,1,20,7,3,0

In [8]:
df2001 = df[(df.year == '2001')]
df2002 = df[(df.year == '2002')]
df2003 = df[(df.year == '2003')]
df2004 = df[(df.year == '2004')]
df2005 = df[(df.year == '2005')]
df2006 = df[(df.year == '2006')]
df2007 = df[(df.year == '2007')]
df2008 = df[(df.year == '2008')]
df2009 = df[(df.year == '2009')]
df2010 = df[(df.year == '2010')]
df2011 = df[(df.year == '2011')]
df2012 = df[(df.year == '2012')]
df2013 = df[(df.year == '2013')]
df2014 = df[(df.year == '2014')]
# renaming inconsistant state names
df= df.replace('delhi ut', 'delhi')
df = df.replace ('a & n islands', 'a&n islands')
df = df.replace ('d & n haveli', 'd&n haveli')
df = df.replace ('d & n haveli', 'd&n haveli')
df.year = df.year.astype(str)
#there are inconsistant names in the districts as well but im going to skip those for now
df

C:\Users\Yasir Hameed\Anaconda3\lib\site-packages\pandas\core\ops.py:716: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = getattr(x, name)(y)

TypeError: invalid type comparison

In [ ]:
df2001.to_csv('crimes_against_women_2001.csv')
df2002.to_csv('crimes_against_women_2002.csv')
df2003.to_csv('crimes_against_women_2003.csv')
df2004.to_csv('crimes_against_women_2004.csv')
df2005.to_csv('crimes_against_women_2005.csv')
df2006.to_csv('crimes_against_women_2006.csv')
df2007.to_csv('crimes_against_women_2007.csv')
df2008.to_csv('crimes_against_women_2008.csv')
df2009.to_csv('crimes_against_women_2009.csv')
df2010.to_csv('crimes_against_women_2010.csv')
df2011.to_csv('crimes_against_women_2011.csv')
df2012.to_csv('crimes_against_women_2012.csv')
df2013.to_csv('crimes_against_women_2013.csv')
df2014.to_csv('crimes_against_women_2014.csv')

In [ ]:
df.pivot_table(index=['state_ut', 'year'], aggfunc=sum)

In [ ]:
table = df.pivot_table(index=['state_ut'] , columns=['year'], aggfunc=sum)

In [ ]:
table.to_csv(table.csv)